name: Deployment of IndoorTracking to Server 2

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      - name: Stop old Application with PM2 stop
        run: |
          pm2 stop pareto-anywhere'

      - name: Update Server
        run: |
          # Kopiert die aktuellen Repository-Dateien zum Zielverzeichnis
          rsync -av --exclude='.git' ./ root@35.235.241.19:/indoortrackingbackend/

      - name: Start App with PM2 
        run: |
          cd /indoortrackingbackend && pm2 start pareto-anywhere'