name: Deployment of IndoorTracking to Server using git pull 22

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Install PM2
        run: sudo npm install pm2 -g || echo "PM2 already installed"

      - name: Stop old Application with PM2
        run: pm2 stop indoor_tracking || echo "Nothing to stop"

      # Stellen Sie sicher, dass Sie zuerst in das Zielverzeichnis wechseln
      - name: Change directory
        run: cd /indoortrackingbackend/

      # Führen Sie git pull aus, um die neuesten Änderungen aus dem Repository zu ziehen
      - name: Pull latest code
        run: |
          cd /indoortrackingbackend/
          sudo git pull origin Development

      # Installieren Sie die Abhängigkeiten im Zielverzeichnis
      - name: Install Dependencies
        run: |
          cd /indoortrackingbackend/
          sudo npm install

      - name: Start App with PM2
        run: pm2 start /indoortrackingbackend/bin/indoor_tracking.js
