name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code
        run: |
          # Hier kommt der Code zum Deployment auf den Server
          # z.B. SSH-Verbindung zum Server herstellen und den Code übertragen