name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Code
        uses: actions/checkout@v2
      
      - name: SSH-Client installieren
        run: sudo apt-get install openssh-client -y
      
      - name: SSH-Schlüssel konfigurieren
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
      - name: Server aktualisieren
        run: |
          ssh root@136.244.89.4 'cd /Indoor_Tracking_Beta && git pull'

