name: Deployment via Git Clone 2

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Delete all PM2 processes
        run: pm2 delete all
      
      - name: Remove existing directory
        run: sudo rm -rf /indoortrackingbackend/

      - name: Clone the repository
        run: git clone https://github.com/YourUsername/YourRepo.git /indoortrackingbackend/

      - name: Install Dependencies
        working-directory: /indoortrackingbackend/
        run: npm install

      - name: Start App with PM2
        run: pm2 start /indoortrackingbackend/bin/indoor_tracking.js
