name: Deploy to Server Management

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install SSH client
        run: sudo apt-get install openssh-client -y
      
      - name: Configure SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        
      - name: Update Server
        run: |
          ssh root@136.244.89.4 'cd /Indoor_Tracking_Beta && git pull'
