name: Deployment of IndoorTracking to Server 2

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      - name: Install PM2
        run: sudo npm install pm2 -g

      - name: Stop old Application with PM2
        run: pm2 stop indoor_tracking || echo "Nothing to stop"

      - name: Copy Files to Target Directory
        run: sudo cp -R . /indoortrackingbackend/

      # Installieren Sie die Abhängigkeiten im Zielverzeichnis
      - name: Install Dependencies at Target
        run: |
          cd /indoortrackingbackend/
          sudo npm install

      - name: Start App with PM2 
        run: pm2 start /home/markus_schmeckenbecher/indoortrackingbackend/bin/indoor_tracking.js