name: Deployment with PM2 Cleanup and Git Clone

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check if any PM2 processes are running
        id: pm2-check
        run: |
          if pm2 list --no-color | grep -q "online"; then
            echo "PM2 processes are running."
            echo "::set-output name=running::true"
          else
            echo "No PM2 processes found."
            echo "::set-output name=running::false"
          fi

      - name: Delete all PM2 processes
        if: steps.pm2-check.outputs.running == 'true'
        run: pm2 delete all
      
      - name: Remove existing directory
        run: sudo rm -rf /indoortrackingbackend/

      - name: Clone the repository
        run: git clone https://github.com/YourUsername/YourRepo.git /indoortrackingbackend/

      - name: Install Dependencies
        working-directory: /indoortrackingbackend/
        run: npm install

      - name: Start App with PM2
        run: pm2 start /indoortrackingbackend/bin/indoor_tracking.js
