name: Deployment of IndoorTracking to Server

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      # Wenn notwendig, können Sie zusätzliche Abhängigkeiten oder Tools installieren. 
      # Zum Beispiel, wenn Sie pm2 nicht global installiert haben:
      - name: Install PM2
        run: sudo npm install pm2 -g

      - name: Stop old Application with PM2
        run: pm2 stop indoor_tracking || echo "Nothing to stop"

      - name: Copy Files to Target Directory
        run: sudo cp -R . /indoortrackingbackend/

      # Starten Sie die App mit PM2, basierend auf Ihrem Start-Skript in package.json
      - name: Start App with PM2 
        run: cd /indoortrackingbackend && pm2 start indoor_tracking