name: Deployment of IndoorTracking to Server

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      - name: SSH-Client installieren
        run: sudo apt-get install openssh-client -y

      - name: SSH-Schlüssel konfigurieren
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop old Application with PM2 stop
        run: |
          ssh root@35.235.241.19 'pm2 stop pareto-anywhere'

      - name: Server aktualisieren
        run: |
          ssh root@35.235.241.19 'cd /indoortrackingbackend && git pull'

      - name: Anwendung mit PM2 starten
        run: |
          ssh root@35.235.241.19 'cd /indoortrackingbackend && pm2 start pareto-anywhere'