name: Deployment of IndoorTracking to Server

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      # Wenn notwendig, können Sie zusätzliche Abhängigkeiten oder Tools installieren. 
      # Zum Beispiel, wenn Sie pm2 nicht global installiert haben:
      - name: Install PM2
        run: npm install pm2 -g

      - name: Stop old Application with PM2
        run: pm2 stop pareto-anywhere

      - name: Copy Files to Target Directory
        run: |
          cp -R . /indoortrackingbackend/

      - name: Start App with PM2 
        run: |
          cd /indoortrackingbackend && pm2 start pareto-anywhere
