name: Deployment of IndoorTracking to Server

on:
  push:
    branches:
      - Development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check Code out
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # ... Ihre anderen Schritte ...

      - name: Kopiert die aktuellen Repository-Dateien zum Zielverzeichnis
        run: rsync -av --exclude='.git' ./ root@35.235.241.19:/indoortrackingbackend/
